### PR TITLE
Community Version 1.0.0

### PR DESCRIPTION
**Pull request by ldittmar81**

### CODE REVIEW

**Comment by Apollon77** [comment]
package.json stuff for testing missing? :-)

**Comment by Apollon77** [comment]
I think the "main" entry is missing in io-package?

**Comment by ldittmar81** [comment]
But now!! :-)

**Comment by Apollon77** [comment]
Sorry, but no :-( https://travis-ci.org/iobroker-community-adapters/ioBroker.find-my-iphone-community/jobs/514120662#L698

**Comment by GermanBluefox** [comment]
Progress?

**Comment by GermanBluefox** [comment]
@ldittmar81 can you finish this? It is just a bit to do :)

**Comment by ldittmar81** [comment]
Next week I got time

**Comment by DutchmanNL** [comment]
let me try to help out here, if not I can always assign back to @ldittmar81 :P

**Comment by DutchmanNL** [comment]
I updated all testing and GitHub actions, but there is a code failure which I can't figure out now please see travis : 

```
https://travis-ci.com/github/ldittmar81/ioBroker.find-my-iphone-community/jobs/319548346#L592-L593
```

@ldittmar81 can you please review my change in your repo, don't get them in this pull not sure why

**Pull request merged**
